In [2]:
import pandas as pd
olx =pd.read_csv('olxPunjab.csv')

In [3]:
olx

     Unnamed: 0                                              Links
0             0  https://www.olx.in/item/s-s-auto-deal-sale-and...
1             1  https://www.olx.in/item/harley-davidson-2017-s...
2             2  https://www.olx.in/item/suzuki-gixxer-sf-150-p...
3             3  https://www.olx.in/item/vikrant-v12-2017-iid-1...
4             4  https://www.olx.in/item/full-ok-koi-bhi-kami-n...
..          ...                                                ...
455         455  https://www.olx.in/item/hero-honda-cd-100ss-ii...
456         456  https://www.olx.in/item/fz-its-like-brand-new-...
457         457  https://www.olx.in/item/dirt-bike-50cc-6-color...
458         458  https://www.olx.in/item/harley-davidson-superl...
459         459  https://www.olx.in/item/all-good-conditons-iid...

[460 rows x 2 columns]

In [4]:
olx.drop(columns=["Unnamed: 0"],inplace=True)

In [5]:
olx

                                                 Links
0    https://www.olx.in/item/s-s-auto-deal-sale-and...
1    https://www.olx.in/item/harley-davidson-2017-s...
2    https://www.olx.in/item/suzuki-gixxer-sf-150-p...
3    https://www.olx.in/item/vikrant-v12-2017-iid-1...
4    https://www.olx.in/item/full-ok-koi-bhi-kami-n...
..                                                 ...
455  https://www.olx.in/item/hero-honda-cd-100ss-ii...
456  https://www.olx.in/item/fz-its-like-brand-new-...
457  https://www.olx.in/item/dirt-bike-50cc-6-color...
458  https://www.olx.in/item/harley-davidson-superl...
459  https://www.olx.in/item/all-good-conditons-iid...

[460 rows x 1 columns]

In [6]:
import selenium
from selenium import webdriver as wb
chr1 = wb.Chrome('C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe')

C:\Users\tswar\AppData\Local\Temp/ipykernel_9416/3578781726.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  chr1 = wb.Chrome('C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe')

In [7]:
from tqdm import tqdm
import numpy
alldetails=[]
erroitems=[]
for t in tqdm(olx.Links):
    chr1.get(t)
    try:
        try:
            Price=chr1.find_element_by_class_name('_2xKfz').text
        except:
            Price='NULL'
        try:
            Brand=chr1.find_element_by_class_name('_2vNpt').text
        except:
            Brand="NULL"
        try:
            Model=chr1.find_elements_by_class_name('_2vNpt')[-3].text
        except:
            Model="NULL"
        try:
            Kilometers=chr1.find_elements_by_class_name('_2vNpt')[-1].text
        except:
            Kilometers="NULL"
        try:
            Manfacture_year=chr1.find_elements_by_class_name('_2vNpt')[-2].text
        except:
            Manfacture_year="NULL"
        try:
            Join_of_candidate=chr1.find_element_by_class_name('_3AdUv')
            Join_of_candidate1=Join_of_candidate.find_elements_by_tag_name('span')
            Join_of_candidate=Join_of_candidate1[-1].text
        except:
            Join_of_candidate="NULL"
        try:
            Location=chr1.find_elements_by_class_name('_2FRXm')[-2].text
        except:
            Location='NULL'
        tempa ={'Bike_price':Price,
                'Km_driven':Kilometers,
                'Make_year':Manfacture_year,
                'Bike_name':Brand,
                'Bike_model':Model,
                "Bike_address":Location,
                'Seller_info':Join_of_candidate,
            }
        alldetails.append(tempa)
    except:
        erroitems.append(t)

  0%|          | 0/460 [00:00<?, ?it/s]C:\Users\tswar\AppData\Local\Temp/ipykernel_9416/1326922503.py:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Price=chr1.find_element_by_class_name('_2xKfz').text
C:\Users\tswar\AppData\Local\Temp/ipykernel_9416/1326922503.py:12: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Brand=chr1.find_element_by_class_name('_2vNpt').text
C:\Users\tswar\AppData\Local\Temp/ipykernel_9416/1326922503.py:16: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Model=chr1.find_elements_by_class_name('_2vNpt')[-3].text
C:\Users\tswar\AppData\Local\Temp/ipykernel_9416/1326922503.py:20: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Kilometers=chr1.find_elements_by_class_name('_2vNpt')[-1].text
C:\Users\tswar\AppData\Local\Temp/ipykernel_9416/1326922503.py:24: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Manfacture_year=chr1.find_elements_by_class_name('_2vNpt')[-2].text
C:\Users\tswar\AppData\Local\Temp/ipykernel_9416/1326922503.py:28: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Join_of_candidate=chr1.find_element_by_class_name('_3AdUv')
C:\Users\tswar\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:359: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")
C:\Users\tswar\AppData\Local\Temp/ipykernel_9416/1326922503.py:34: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Location=chr1.find_elements_by_class_name('_2FRXm')[-2].text
100%|██████████| 460/460 [54:41<00:00,  7.13s/it]

In [8]:
len(alldetails)

460

In [12]:
dlf=pd.DataFrame((alldetails))
dlf.to_csv('Olx_Punjab.csv')

In [11]:
dlf

,Bike_price,Km_driven,Make_year,Bike_name,Bike_model,Bike_address,Seller_info
0,"₹ 2,10,000","5,000 km",2018,KTM,390 Duke ABS,"Sector 63, Mohali, Punjab",May 2016
1,"₹ 4,00,000","13,000 km",2017,Other Brands,Others,"Sector 63, Mohali, Punjab",May 2016
2,"₹ 1,25,000","11,000 km",2021,Suzuki,Gixxer,"Sector 63, Mohali, Punjab",May 2016
3,"₹ 33,000","30,000 km",2017,Bajaj,Others,"S Labh Singh Dharni Colony, Bhadson, Punjab",Nov 2019
4,"₹ 32,000","73,000 km",2012,Bajaj,Discover,"Ward No 7, Mukerian, Punjab",Apr 2021
...,...,...,...,...,...,...,...
455,"₹ 35,000","1,000 km",2006,Hero Honda,CD 100,"New Kundanpuri, Ludhiana, Punjab",Aug 2019
456,"₹ 45,000","30,000 km",2014,Yamaha,FZ,"Mahavir Nagar, Ludhiana, Punjab",Jul 2013
457,"₹ 25,000",0 km,2021,Other Brands,Others,"Vishal Nagar, Bathinda, Punjab",Jun 2021
458,"₹ 3,75,000","15,000 km",2013,Other Brands,Others,"New Golden Avenue, Amritsar, Punjab",Sep 2020
459,"₹ 32,000","35,309 km",2012,Hero,Splendor,"Chander Colony, Tarantaran, Punjab",3 days ago

In [ ]:
Join_of_candidate=chr1.find_element_by_class_name('_3AdUv')
Join_of_candidate1=Join_of_candidate.find_elements_by_tag_name('span')